### ISSUE TITLE
Mock `lpush` isn't O(1)

### ISSUE THREAD

**Issue by elliot42** [andrewberls/predis#7]
At least as of 0.1.4, the `lpush` operation usings `(cons item [...])`, which is an O(N) operation instead of an O(1) operation.  `(cons item (list))` will work in constant time, but will break the test suite since now that data will be a list instead of a vector as the tests expect.  Putting a note here so can fix when time available.

**Comment by andrewberls** [comment]
As mentioned in https://github.com/andrewberls/predis/pull/6#issuecomment-121457149 , offering the same time complexity guarantees is not a goal of the library. Furthermore I haven't made a strong conscious effort to enforce that `list` datatype keys are always Clojure `lists` or `vectors`, since the difference is largely glossed over with Clojure's seq abstractions. Probably worth going over at some point

**Comment by elliot42** [comment]
This is now addressed (sort of well enough for now) in the updated PR, closing out
